# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentfiles < Formula
  desc "Standardize AI coding-agent instruction files across repositories"
  homepage "https://github.com/davaba86/agentfiles"
  version "0.1.2"
  license "MIT"

  on_macos do
    url "https://github.com/davaba86/agentfiles/releases/download/v0.1.2/agentfiles_0.1.2_darwin_all.tar.gz"
    sha256 "65d68963de246fa3e77f2fb613f3f9e85d80aa1aa635edc8a010038e2a423ed3"

    define_method(:install) do
      bin.install "agentfiles"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davaba86/agentfiles/releases/download/v0.1.2/agentfiles_0.1.2_linux_amd64.tar.gz"
      sha256 "75d42537a83fa649b0cad3767a5752356625f64a761c9dae74acf09216801fa1"
      define_method(:install) do
        bin.install "agentfiles"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davaba86/agentfiles/releases/download/v0.1.2/agentfiles_0.1.2_linux_arm64.tar.gz"
      sha256 "d38a878ddbc7e9edd184a676f9e5cf747b5203caa136391952aca8364282dedc"
      define_method(:install) do
        bin.install "agentfiles"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentfiles version")
  end
end
