# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentfiles < Formula
  desc "Standardize AI coding-agent instruction files across repositories"
  homepage "https://github.com/davaba86/agentfiles"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davaba86/agentfiles/releases/download/v0.1.1/agentfiles_0.1.1_darwin_amd64.tar.gz"
      sha256 "d3bef7a1314d922d294d05667b305ce3976af4601f9f30900c90d048b3a48b59"

      define_method(:install) do
        bin.install "agentfiles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davaba86/agentfiles/releases/download/v0.1.1/agentfiles_0.1.1_darwin_arm64.tar.gz"
      sha256 "d61d5ee44cfdb7d3b1400996283a0cad20b15273ecd1aeda770a587c5e1a99b4"

      define_method(:install) do
        bin.install "agentfiles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davaba86/agentfiles/releases/download/v0.1.1/agentfiles_0.1.1_linux_amd64.tar.gz"
      sha256 "0d779105441faef725553c08a6e08ff76101b77cf3348c0a45c3dffb37358522"
      define_method(:install) do
        bin.install "agentfiles"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davaba86/agentfiles/releases/download/v0.1.1/agentfiles_0.1.1_linux_arm64.tar.gz"
      sha256 "fe198dd57b58fac1d8a88d2a228e9cc5c4f6712c7542471a8490fbfffe4213fb"
      define_method(:install) do
        bin.install "agentfiles"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentfiles version")
  end
end
